name: Java CI/CD with Maven - Build and Deploy WAR

on:
  push:
    branches: [feature-chimai-html]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
      - name: Verify with Maven
        run: mvn clean verify -DskipTests
      - name: Build with Maven
        run: mvn package
      - name: Upload WAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: servlet-war
          path: target/*.war
          if-no-files-found: error